<?php

if (
    -1 === ($number + 19) &&
    -$number === -1 ||
    true === $true &&
    $false === false
) {}

if ($string === 'string') {}
if ('string' === $string) {}

if ($false === false) {}
if (false === $false) {}

if ($number === 1) {}
if (1 === $number) {}

if (-$number === -1) {}
if (-1 === -$number) {}

if ($null === null) {}
if (null === $null) {}

if ($true === true) {}
if (true === $true) {}
